### ISSUE TITLE
correcte taal attribute value

### ISSUE THREAD

**Issue by tom-2810** [OvenMagnetron/oba#1]
als je content Nederlands is, kan je dit ook aangeven in je html element met "nl" in plaats van "en".

https://github.com/OvenMagnetron/oba/blob/16926ce7fe1b8fb0df30a549aafd9cf72d5d0b3a/uitleengeschiedenis/index.html#L2

**Comment by Patrickkhr** [comment]
De issue is opgelost, bedankt! https://github.com/OvenMagnetron/oba/blob/1b041e77e352a0c621384466218e1e93c5117c93/uitleningen-en-verlengen/index.html#L2
