### ISSUE TITLE
een li element kan je beter in een ul zetten

### ISSUE THREAD

**Issue by YoussraElmortai** [OvenMagnetron/oba#2]
https://github.com/OvenMagnetron/oba/blob/16926ce7fe1b8fb0df30a549aafd9cf72d5d0b3a/index.html#L41
<img width="775" alt="image" src="https://github.com/OvenMagnetron/oba/assets/112857270/b9523e08-4438-410e-9a5a-03399ca8b62d">

**Comment by Patrickkhr** [comment]
We hebben het gefixed, bedankt!
https://github.com/OvenMagnetron/oba/blob/1b041e77e352a0c621384466218e1e93c5117c93/uitleningen-en-verlengen/index.html#L41-L46
