### ISSUE TITLE
h1 mist in document

### ISSUE THREAD

**Issue by tom-2810** [OvenMagnetron/oba#3]
Je document mist een h1 element en begint bij h2. Deze pagina heeft daarom eigenlijk geen titel. Kijk anders eens naar de web dev extension van Chrome.  https://chrome.google.com/webstore/detail/web-developer/bfbameneiokkgbdmiekhjnmfkcnldhhm 
Met View Document Outline onder Information kan je deze heading volgorde checken.

<img width="855" alt="Screenshot 2023-09-29 at 11 22 03" src="https://github.com/OvenMagnetron/oba/assets/112861614/a3626578-ee69-436a-993f-61814485f5cc">

**Comment by Jesse-Kramer** [comment]
Gefixed!
