### ISSUE TITLE
missing ul for list

### ISSUE THREAD

**Issue by christoph3r3w** [OvenMagnetron/oba#4]
the list need to be surrounded by an ul

![feedback patrick](https://github.com/OvenMagnetron/oba/assets/144007933/c9e978af-9fde-4460-8c23-4a074046dc5c)

https://github.com/OvenMagnetron/oba/blob/c69dd47df6ba4d92c742833f1162e44047ffd8cc/uitleningen-en-verlengen/index.html#L41-L46

**Comment by Patrickkhr** [comment]
We hebben het gefixed, bedankt!
https://github.com/OvenMagnetron/oba/blob/1b041e77e352a0c621384466218e1e93c5117c93/uitleningen-en-verlengen/index.html#L41-L46
